all:
	PENGLAI_SDK=$(PENGLAI_SDK) make -C host
	PENGLAI_SDK=$(PENGLAI_SDK) make -C prime
	#PENGLAI_SDK=$(PENGLAI_SDK) make -C aes
	#PENGLAI_SDK=$(PENGLAI_SDK) make -C mem
	#PENGLAI_SDK=$(PENGLAI_SDK) make -C crypt
clean:
	make -C host clean
	make -C prime clean
	#make -C aes clean
	#make -C mem clean
	#make -C crypt clean
